dir: '{{.InterfaceDir}}/mocks'
filename: '{{.InterfaceName}}.go'
packages:
  OrderService/internal/service:
    interfaces:
      OrderRepo:
      Cache:
  OrderService/pkg/trm:
    interfaces:
      Manager:
